#!/bin/bash
# Usage: ./set-dev <repo> [package [org]] [--http]
# Org defaults to 'pcdshub', package defaults to repo name
# Defaults to ssh remote, use --http if you prefer that
set -e

if [ -z "$1" ]; then
  echo "Usage: ./set-dev <repo> [package [org]]" >&2
  exit 1
fi

REPO="$1"
PACKAGE=${2:-${REPO}}
ORG=${3:-"pcdshub"}

HERE="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
mkdir -p "${HERE}/dev/devpath"

cd "${HERE}/dev"

if [ ! -d "${REPO}" ]; then
  # shellcheck disable=SC2199
  if [[ "$@" =~ "--http" ]]; then
    git clone "https://github.com/${ORG}/${REPO}.git"
  else
    git clone "git@github.com:${ORG}/${REPO}.git"
  fi
fi

ln -s "$(readlink -f "${REPO}/${PACKAGE}")" "devpath/${PACKAGE}"
