#!/bin/bash
# Source this to load the full environment that hutch python uses

USE_LOCAL="0"
export CONDA_ENVNAME="pcds-4.1.1"

export HUTCH="tst"
export NFS_BASE="/reg/g/pcds/pyps/conda/py36"

if [ -n "${USE_LOCAL}" ] && [ -d "${LOCAL_BASE}" ]; then
  echo "Loading local disk python env ${CONDA_ENVNAME}"
  source "${LOCAL_BASE}/${CONDA_ENVNAME}/bin/activate"
else
  echo "Loading NFS python env ${CONDA_ENVNAME}"
  source "${NFS_BASE}/etc/profile.d/conda.sh"
  conda activate "${CONDA_ENVNAME}"
fi

unset PYTHONPATH
unset LD_LIBRARY_PATH

HERE=`dirname $(readlink -f $BASH_SOURCE)`

export PYTHONPATH="${HERE}:${HERE}/dev/devpath:${HERE}/../common/dev/devpath"
# source pcdsdaq_lib_setup
export CONDA_PROMPT_MODIFIER="(${HUTCH}-${CONDA_ENVNAME})"
