#!/bin/bash
# Source this to load the full environment that hutch python uses

USE_LOCAL="0"
export CONDA_ENVNAME="pcds-5.3.0"
export CONDA_BASE="/cds/group/pcds/pyps/conda/py39"
export HUTCH="tst"

unset PYTHONPATH
unset LD_LIBRARY_PATH

if [ -n "${USE_LOCAL}" ] && [ -d "${LOCAL_BASE}" ]; then
echo "Loading local disk python env ${CONDA_ENVNAME}"
source "${LOCAL_BASE}/${CONDA_ENVNAME}/bin/activate"
else
echo "Loading NFS python env ${CONDA_ENVNAME}"
source "${CONDA_BASE}/etc/profile.d/conda.sh"
conda activate "${CONDA_ENVNAME}"
fi
HERE=`dirname $(readlink -f $BASH_SOURCE)`

if [ -f "${HERE}/../common/dev/hutch-python/bin/hutch-python" ]; then
    export PATH="${HERE}../common/dev/hutch-python/bin:${PATH}"
fi

export PYTHONPATH="${HERE}:${HERE}/dev/devpath:${HERE}/../common/dev/devpath"
# source pcdsdaq_lib_setup
export CONDA_PROMPT_MODIFIER="(${HUTCH}-${CONDA_ENVNAME})"
